### ISSUE TITLE
Avatar sync broken after upgrade from 17.0.0 to 17.0.1

### ISSUE THREAD

**Issue by ClundXIII** [nextcloud/ldap_write_support#106] opened 2019-12-27 12:58 UTC
Hi,

after the upgrade it seems that avatars are no longer being synchronized. I am also not able to set an avatar in my profile. It just says "Picture provided by original account".

Is there any change between v.1 and .2 that now prevents this?

I am using inetOrgPerson as my user account class.

**Comment by mistergibson** [comment] 2019-12-27 21:21
I am also having this issue with 16.0.6. I have checked the option to allow users to set their avatars, but all I get is "Picture provided by original account" as if it is read-only. Clearly a bug, but I'm curious when/where it decides to call it 'read-only' and not present the avatar set option.

**Comment by ClundXIII** [comment] 2020-01-05 11:22
Actually I just now upgraded to .2

The problem still persists.

**Comment by blizzz** [comment] 2020-01-06 16:49
A shoot into the blue, as I didn't look closer into it, but could it be it is caused by https://github.com/nextcloud/server/pull/17002? It was released with 17.0.1.

**Comment by ClundXIII** [comment] 2020-01-10 09:29
I figured out the issue. It is CRON.

Because it is supposed to run all 5 Minutes the cron process locked up the profile, piled up and clogged my RAM. I lowered the frequency of cron and now I can upload a profile picture.

**Comment by blizzz** [comment] 2020-01-15 15:30
This sounds rather like an issue on server than, not here.

Do you have more insights what exactly was locked (database? files?). I am not sure why this should clog RAM.

**Comment by ClundXIII** [comment] 2020-01-29 22:10
> Do you have more insights what exactly was locked (database? files?). I am not sure why this should clog RAM.

I have no idea. However the latest updates increased the performance significantly. I can now search the user more reliable.

Feel free to close this issue

**Closed** 2020-01-30 21:28 UTC
